name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Foundry build
        uses: actions/cache@v3
        with:
          path: ~/.foundry
          key: ${{ runner.os }}-foundry-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-foundry-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Ensure Foundry is up to date
        run: foundryup

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt

      - name: Run Forge build
        run: forge build --sizes
        id: build

      - name: Run Forge tests
        run: forge test -vvv
        id: test
        env:
          # If your contract requires Chainlink or external data, set a fork URL
          FOUNDRY_ETH_RPC_URL: https://sepolia.infura.io/v3/2e2c861981fc4783b03dae827b0bf145
